services:
  photoprism:
    image: photoprism/photoprism:latest
    hostname: photoprism
    stop_grace_period: 10s
    networks:
      - traefik-proxy
    environment:
      PHOTOPRISM_CONFIG_PATH: /etc/photoprism/options.yml
    volumes:
      - /appdata/photoprism/storage:/photoprism/storage
      - /mnt/source:/photoprism/originals:ro
    configs:
      - source: photoprism_options
        target: /etc/photoprism/options.yml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nas == synology-nas
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.photoprism.rule=Host(`photoprism.regularlab.xyz`)"
        - "traefik.http.routers.photoprism.entrypoints=web"
        - "traefik.http.services.photoprism.loadbalancer.server.port=2342"

configs:
  photoprism_options:
    external: true

networks:
  traefik-proxy:
    external: true
