http:
  routers:
    dozzle:
      rule: "Host(`dozzle.regularlab.xyz`)"
      entryPoints:
        - web
      service: dozzle

  services:
    dozzle:
      loadBalancer:
        servers:
          - url: "http://100.110.14.83:8888"
