apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
    api:
      dashboard: true
      insecure: false
    logs:
      general:
        level: ERROR
      access:
        enabled: true
    metrics:
      prometheus:
        enabled: true
