services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - /appdata/jellyfin/config:/config
      - /appdata/jellyfin/cache:/cache
      - /mnt/source/vid:/media:ro
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nas == true
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.regularlab.xyz`)"
        - "traefik.http.routers.jellyfin.entrypoints=web"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "homepage.name=Jellyfin"
        - "homepage.href=http://jellyfin.regularlab.xyz"
        - "homepage.group=Media"
        - "homepage.description=Media server"
        - "homepage.icon=jellyfin"

networks:
  traefik-proxy:
    external: true
