services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_shows:/data/shows:ro
      - jellyfin_movies:/data/movies:ro
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nas == synology-nas
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.regularlab.xyz`)"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  traefik-proxy:
    external: true

volumes:
  jellyfin_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.3,rw,nfsvers=4,hard,intr
      device: ":/volume1/appdata/jellyfin/config"
  jellyfin_cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.3,rw,nfsvers=4,hard,intr
      device: ":/volume1/appdata/jellyfin/cache"
  jellyfin_shows:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.3,ro,nfsvers=4,hard,intr
      device: ":/volume1/data/media/shows"
  jellyfin_movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.10.10.3,ro,nfsvers=4,hard,intr
      device: ":/volume1/data/media/movies"
