services:
  photoview:
    image: photoview/photoview:2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    hostname: photoview
    stop_grace_period: 10s
    networks:
      - traefik-proxy
    environment:
      PHOTOVIEW_DATABASE_DRIVER: sqlite
      PHOTOVIEW_SQLITE_PATH: /appdata/photoview/photoview.db
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
    volumes:
      - /appdata/photoview/database:/home/photoview/database
      - /appdata/photoview/storage:/home/photoview/media-cache
      - /mnt/source:/photos:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nas == true
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.photoview.rule=Host(`photoview.regularlab.xyz`)"
        - "traefik.http.routers.photoview.entrypoints=web"
        - "traefik.http.services.photoview.loadbalancer.server.port=80"
networks:
  traefik-proxy:
    external: true