name: photoprism

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    environment:
      PHOTOPRISM_ADMIN_USER: ${ADMIN_USER:-admin}
      PHOTOPRISM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PHOTOPRISM_SITE_URL: ${SITE_URL}
      PHOTOPRISM_DATABASE_DRIVER: sqlite
      # OIDC / Authentik
      PHOTOPRISM_OIDC_URI: ${OIDC_URI}
      PHOTOPRISM_OIDC_CLIENT: ${OIDC_CLIENT}
      PHOTOPRISM_OIDC_SECRET: ${OIDC_SECRET}
      PHOTOPRISM_OIDC_SCOPES: "openid email profile"
      PHOTOPRISM_OIDC_PROVIDER: "Authentik"
      PHOTOPRISM_OIDC_REGISTER: "true"
    volumes:
      - /appdata/photoprism/storage:/photoprism/storage
      - ${PHOTOS_PATH}:/photoprism/originals
    ports:
      - "2342:2342"
